//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTPRODB.DatabaseCommunication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DbStructure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbStructure() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTPRODB.DatabaseCommunication.Resources.DbStructure", typeof(DbStructure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE Item
        ///ADD FOREIGN KEY (Producer_ID) REFERENCES Producer(ID);
        ///
        ///ALTER TABLE Rubber
        ///ADD FOREIGN KEY (Item_ID) REFERENCES Item(ID);
        ///
        ///ALTER TABLE Blade
        ///ADD FOREIGN KEY (Item_ID) REFERENCES Item(ID);
        ///
        ///ALTER TABLE Pips
        ///ADD FOREIGN KEY (Item_ID) REFERENCES Item(ID);.
        /// </summary>
        internal static string AddForeignKeys {
            get {
                return ResourceManager.GetString("AddForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Item
        ///(
        ///    ID int NOT NULL PRIMARY KEY,
        ///    Name text NOT NULL,
        ///	Url text NOT NULL,
        ///    Producer_ID int NOT NULL,
        ///	Ratings int NOT NULL,	
        ///);
        ///
        ///CREATE TABLE Producer
        ///(
        ///    ID int NOT NULL PRIMARY KEY,
        ///    Name text NOT NULL	
        ///);
        ///
        ///CREATE TABLE Rubber
        ///(
        ///    ID int NOT NULL PRIMARY KEY,
        ///    Item_ID int NOT NULL,
        ///	Speed real,
        ///    Spin real,
        ///    Control real,
        ///    Tackiness real,
        ///    Weight real,
        ///    Hardness real,
        ///    Gears real,
        ///    Throw_Angle real,
        ///    Consistency real,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTables {
            get {
                return ResourceManager.GetString("CreateTables", resourceCulture);
            }
        }
    }
}
