ALTER TABLE Items
ADD FOREIGN KEY (Producer_ID) REFERENCES Producers(ID);

ALTER TABLE Rubbers
ADD FOREIGN KEY (Item_ID) REFERENCES Items(ID);

ALTER TABLE Blades
ADD FOREIGN KEY (Item_ID) REFERENCES Items(ID);

ALTER TABLE Pips
ADD FOREIGN KEY (Item_ID) REFERENCES Items(ID);